require SQLAlchemy < 1.2
The current code is incompatible with SQLAlchemy 1.2:

    Traceback (most recent call last):
      File "…/venv.py3/lib64/python3.7/site-packages/ddt.py", line 145, in wrapper
        return func(self, *args, **kwargs)
      File "…/schwarz/column_alchemy/tests/enum_column_test.py", line 37, in test_can_store_and_load_values
        db_value = session.query(table).limit(1).scalar()
      File "…/venv.py3/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 2866, in scalar
        ret = self.one()
      File "…/venv.py3/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 2837, in one
        ret = self.one_or_none()
      File "…/venv.py3/lib64/python3.7/site-packages/sqlalchemy/orm/query.py", line 2807, in one_or_none
        ret = list(self)
      File "…/venv.py3/lib64/python3.7/site-packages/sqlalchemy/orm/loading.py", line 97, in instances
        util.raise_from_cause(err)
      File "…/venv.py3/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb, cause=cause)
      File "…/venv.py3/lib64/python3.7/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
        raise value
      File "…/venv.py3/lib64/python3.7/site-packages/sqlalchemy/orm/loading.py", line 81, in instances
        for row in fetch]
      File "…/venv.py3/lib64/python3.7/site-packages/sqlalchemy/orm/loading.py", line 81, in <listcomp>
        for row in fetch]
      File "…/venv.py3/lib64/python3.7/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
        rows = [keyed_tuple([proc(row) for proc in process])
      File "…/venv.py3/lib64/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1484, in process
        value = self._object_value_for_elem(value)
      File "…/venv.py3/lib64/python3.7/site-packages/sqlalchemy/sql/sqltypes.py", line 1405, in _object_value_for_elem
        '"%s" is not among the defined enum values' % elem)
    LookupError: "zwei" is not among the defined enum values